#!/bin/bash

#Your database username
DBUSER=dbuser

#Your database password
DBPASS=dbpass

#Database name
DBNAME=dbname

#Contest start time
STARTTIME=`date -d '1 minute' +"%F %H:%M:%S"`

#Contest end time
ENDTIME=`date -d '1 hour' +"%F %H:%M:%S"`

rm *~ 2> /dev/null
rm statistics/*~ 2> /dev/null
rm problems/*/*~ 2> /dev/null

chmod 777 code
chmod 666 problems/*/statement
chmod 755 onj

sed -i "s/dbuser/$DBUSER/g" settings.php
sed -i "s/dbpass/$DBPASS/g" settings.php
sed -i "s/dbname/$DBNAME/g" settings.php dbinit.sql
sed -i "s/STARTTIME/$STARTTIME/g" settings.php
sed -i "s/ENDTIME/$ENDTIME/g" settings.php

if [ $DBPASS ]; then
	echo "drop database $DBNAME" | mysql -u"$DBUSER" -p"$DBPASS" 2> /dev/null
	mysql -u"$DBUSER" -p"$DBPASS" < dbinit.sql
else
	echo "drop database $DBNAME" | mysql -u"$DBUSER" 2> /dev/null
	mysql -u"$DBUSER" < dbinit.sql
fi

#Generate random strings for the code and problem directories
JUNK=$(date | md5sum | md5sum)
APPEND=${JUNK:0:20}
CODEDIR=code_$APPEND
PROBLEMDIR=problems_$APPEND

sed -i "s/codedir/$CODEDIR/g" settings.php
sed -i "s/problemdir/$PROBLEMDIR/g" settings.php

mv code $CODEDIR
mv problems $PROBLEMDIR
